server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clabdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.clab.**.dto

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.clab: debug

clab:
  jwt:
    access-expmin: 60
    refresh-expmin: 1
    secret-string: 4sP3z3euxNgx5GLCw5ExlwxpYB575myDQ3y27mtzYgblL7ofNzbd6Obz41zSQz4SFIG+rATcRUTKxRAXnMVexQ==

upload:
  local:
    dir: src/main/resources/uploads